version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: ticket-booking-db
    environment:
      POSTGRES_DB: ticket_booking
      POSTGRES_USER: ticket_user
      POSTGRES_PASSWORD: ticket_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./migrations:/docker-entrypoint-initdb.d/migrations
      - ./scripts:/docker-entrypoint-initdb.d/scripts
      - ./init-db.sh:/docker-entrypoint-initdb.d/init-db.sh
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ticket_user -d ticket_booking"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: ticket-booking-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_USER: ticket_user
      DB_PASSWORD: ticket_password
      DB_NAME: ticket_booking
      DB_SSL_MODE: disable
      LOG_LEVEL: debug
    depends_on:
      postgres:
        condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 10s

volumes:
  postgres_data: 