// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://kjihnazxnyvhduguwtmw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImtqaWhuYXp4bnl2aGR1Z3V3dG13Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3ODIzNTUsImV4cCI6MjA2NzM1ODM1NX0.2BhI-_VEu-JWw_BtUyngnXxo5aDjELafDxGuMd2LMXY";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});